[package]
name = "clovalink_core"
version = "0.1.6"
edition = "2021"

[dependencies]
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
lettre = { workspace = true }
regex = { workspace = true }
totp-rs = { workspace = true }
redis = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
types = { workspace = true }

# S3 Replication
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-credential-types = { workspace = true }

