-- 008_expand_varchar_lengths.sql
-- 将字段长度由 32 扩容至 64/128，支持 UUID 格式的用户 ID (36字符) 及更长的固件编号

ALTER TABLE app ALTER COLUMN createby_id TYPE VARCHAR(64);
ALTER TABLE app ALTER COLUMN createby_name TYPE VARCHAR(64);
ALTER TABLE app ALTER COLUMN gitlab_id TYPE VARCHAR(64);
ALTER TABLE app ALTER COLUMN number TYPE VARCHAR(64);

ALTER TABLE app_deploy ALTER COLUMN number TYPE VARCHAR(64);
ALTER TABLE app_deploy ALTER COLUMN app_no TYPE VARCHAR(64);

ALTER TABLE app_class ALTER COLUMN number TYPE VARCHAR(64);

ALTER TABLE app_user ALTER COLUMN app_no TYPE VARCHAR(64);
ALTER TABLE app_user ALTER COLUMN uid TYPE VARCHAR(64) USING uid::text;

ALTER TABLE app_config ALTER COLUMN number TYPE VARCHAR(64);
