//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "departments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::file_groups::Entity")]
    FileGroups,
    #[sea_orm(has_many = "super::file_requests::Entity")]
    FileRequests,
    #[sea_orm(has_many = "super::files_metadata::Entity")]
    FilesMetadata,
    #[sea_orm(has_many = "super::sso_attribute_mappings::Entity")]
    SsoAttributeMappings,
    #[sea_orm(has_many = "super::tenant_oidc_providers::Entity")]
    TenantOidcProviders,
    #[sea_orm(has_many = "super::tenant_saml_providers::Entity")]
    TenantSamlProviders,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tenants,
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
}

impl Related<super::file_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileGroups.def()
    }
}

impl Related<super::file_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileRequests.def()
    }
}

impl Related<super::files_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FilesMetadata.def()
    }
}

impl Related<super::sso_attribute_mappings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SsoAttributeMappings.def()
    }
}

impl Related<super::tenant_oidc_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantOidcProviders.def()
    }
}

impl Related<super::tenant_saml_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantSamlProviders.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
