//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "extension_event_triggers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub extension_id: Uuid,
    pub event_type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub filter_config: Json,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::extensions::Entity",
        from = "Column::ExtensionId",
        to = "super::extensions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Extensions,
}

impl Related<super::extensions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Extensions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
