//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "extension_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub extension_id: Uuid,
    pub version: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub manifest: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub changelog: Option<String>,
    pub is_current: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::extension_installations::Entity")]
    ExtensionInstallations,
    #[sea_orm(
        belongs_to = "super::extensions::Entity",
        from = "Column::ExtensionId",
        to = "super::extensions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Extensions,
}

impl Related<super::extension_installations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtensionInstallations.def()
    }
}

impl Related<super::extensions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Extensions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
