//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "extension_permissions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub installation_id: Uuid,
    pub permission: String,
    pub granted_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::extension_installations::Entity",
        from = "Column::InstallationId",
        to = "super::extension_installations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ExtensionInstallations,
}

impl Related<super::extension_installations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtensionInstallations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
