//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "extensions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub name: String,
    pub slug: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub extension_type: String,
    #[sea_orm(column_type = "Text")]
    pub manifest_url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub webhook_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub public_key: Option<String>,
    pub signature_algorithm: String,
    pub status: String,
    pub allowed_tenant_ids: Option<Vec<Uuid>>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::automation_jobs::Entity")]
    AutomationJobs,
    #[sea_orm(has_many = "super::extension_event_triggers::Entity")]
    ExtensionEventTriggers,
    #[sea_orm(has_many = "super::extension_installations::Entity")]
    ExtensionInstallations,
    #[sea_orm(has_many = "super::extension_versions::Entity")]
    ExtensionVersions,
    #[sea_orm(has_many = "super::extension_webhook_logs::Entity")]
    ExtensionWebhookLogs,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tenants,
}

impl Related<super::automation_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AutomationJobs.def()
    }
}

impl Related<super::extension_event_triggers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtensionEventTriggers.def()
    }
}

impl Related<super::extension_installations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtensionInstallations.def()
    }
}

impl Related<super::extension_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtensionVersions.def()
    }
}

impl Related<super::extension_webhook_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtensionWebhookLogs.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
