//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "extension_installations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub extension_id: Uuid,
    pub tenant_id: Uuid,
    pub version_id: Uuid,
    pub enabled: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub settings: Json,
    pub installed_by: Option<Uuid>,
    pub installed_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::extension_permissions::Entity")]
    ExtensionPermissions,
    #[sea_orm(
        belongs_to = "super::extension_versions::Entity",
        from = "Column::VersionId",
        to = "super::extension_versions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ExtensionVersions,
    #[sea_orm(
        belongs_to = "super::extensions::Entity",
        from = "Column::ExtensionId",
        to = "super::extensions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Extensions,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tenants,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::InstalledBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::extension_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtensionPermissions.def()
    }
}

impl Related<super::extension_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtensionVersions.def()
    }
}

impl Related<super::extensions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Extensions.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
