//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "file_request_uploads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub file_request_id: Uuid,
    pub file_metadata_id: Option<Uuid>,
    pub filename: String,
    pub original_filename: String,
    pub size_bytes: i64,
    pub content_type: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub storage_path: String,
    pub uploaded_by_email: Option<String>,
    pub uploaded_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::file_requests::Entity",
        from = "Column::FileRequestId",
        to = "super::file_requests::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FileRequests,
    #[sea_orm(
        belongs_to = "super::files_metadata::Entity",
        from = "Column::FileMetadataId",
        to = "super::files_metadata::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    FilesMetadata,
}

impl Related<super::file_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileRequests.def()
    }
}

impl Related<super::files_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FilesMetadata.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
