//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "files_metadata")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub department_id: Option<Uuid>,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub storage_path: String,
    pub size_bytes: i64,
    pub content_type: Option<String>,
    pub is_directory: bool,
    pub owner_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_path: Option<String>,
    pub visibility: String,
    pub is_company_folder: Option<bool>,
    pub version: Option<i32>,
    pub version_parent_id: Option<Uuid>,
    pub is_immutable: Option<bool>,
    pub is_locked: bool,
    pub locked_by: Option<Uuid>,
    pub locked_at: Option<DateTimeWithTimeZone>,
    pub lock_password_hash: Option<String>,
    pub lock_requires_role: Option<String>,
    pub content_hash: Option<String>,
    #[sea_orm(unique)]
    pub ulid: Option<String>,
    pub is_deleted: bool,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub scan_status: Option<String>,
    pub group_id: Option<Uuid>,
    pub approval_status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::approval_requests::Entity")]
    ApprovalRequests,
    #[sea_orm(
        belongs_to = "super::departments::Entity",
        from = "Column::DepartmentId",
        to = "super::departments::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Departments,
    #[sea_orm(has_many = "super::file_comments::Entity")]
    FileComments,
    #[sea_orm(has_many = "super::file_embeddings::Entity")]
    FileEmbeddings,
    #[sea_orm(has_many = "super::file_exports::Entity")]
    FileExports,
    #[sea_orm(
        belongs_to = "super::file_groups::Entity",
        from = "Column::GroupId",
        to = "super::file_groups::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    FileGroups,
    #[sea_orm(has_many = "super::file_request_uploads::Entity")]
    FileRequestUploads,
    #[sea_orm(has_many = "super::file_shares::Entity")]
    FileShares,
    #[sea_orm(has_one = "super::file_summaries::Entity")]
    FileSummaries,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::VersionParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tenants,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::LockedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
    #[sea_orm(has_one = "super::virus_scan_jobs::Entity")]
    VirusScanJobs,
    #[sea_orm(has_many = "super::virus_scan_results::Entity")]
    VirusScanResults,
}

impl Related<super::approval_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApprovalRequests.def()
    }
}

impl Related<super::departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Departments.def()
    }
}

impl Related<super::file_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileComments.def()
    }
}

impl Related<super::file_embeddings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileEmbeddings.def()
    }
}

impl Related<super::file_exports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileExports.def()
    }
}

impl Related<super::file_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileGroups.def()
    }
}

impl Related<super::file_request_uploads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileRequestUploads.def()
    }
}

impl Related<super::file_shares::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileShares.def()
    }
}

impl Related<super::file_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileSummaries.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl Related<super::virus_scan_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VirusScanJobs.def()
    }
}

impl Related<super::virus_scan_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VirusScanResults.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
