//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "saml_consumed_assertions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub assertion_id: String,
    pub provider_id: Uuid,
    pub consumed_at: DateTimeWithTimeZone,
    pub not_on_or_after: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tenant_saml_providers::Entity",
        from = "Column::ProviderId",
        to = "super::tenant_saml_providers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TenantSamlProviders,
}

impl Related<super::tenant_saml_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantSamlProviders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
