//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sso_attribute_mappings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub protocol: String,
    pub provider_id: Uuid,
    pub attribute_name: String,
    pub attribute_value: String,
    pub match_type: String,
    pub target_role: String,
    pub target_custom_role_id: Option<Uuid>,
    pub target_department_id: Option<Uuid>,
    pub priority: i32,
    pub enabled: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::departments::Entity",
        from = "Column::TargetDepartmentId",
        to = "super::departments::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Departments,
    #[sea_orm(
        belongs_to = "super::roles::Entity",
        from = "Column::TargetCustomRoleId",
        to = "super::roles::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Roles,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tenants,
}

impl Related<super::departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Departments.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
