//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tenant_saml_providers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub name: String,
    pub slug: String,
    pub provider_type: String,
    #[sea_orm(column_type = "Text")]
    pub idp_entity_id: String,
    #[sea_orm(column_type = "Text")]
    pub idp_sso_url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub idp_slo_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub idp_metadata_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub idp_metadata_xml: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub idp_signing_certificate: String,
    #[sea_orm(column_type = "Text")]
    pub sp_entity_id: String,
    pub nameid_format: String,
    pub request_signing: bool,
    pub want_assertions_signed: bool,
    pub want_response_signed: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub sp_signing_key_encrypted: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sp_signing_cert: Option<String>,
    pub sso_binding: String,
    pub attribute_email: String,
    pub attribute_name: String,
    pub auto_provision: bool,
    pub default_role: String,
    pub default_custom_role_id: Option<Uuid>,
    pub default_department_id: Option<Uuid>,
    pub email_domains: Vec<String>,
    pub trust_idp_mfa: bool,
    pub enabled: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::departments::Entity",
        from = "Column::DefaultDepartmentId",
        to = "super::departments::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Departments,
    #[sea_orm(
        belongs_to = "super::roles::Entity",
        from = "Column::DefaultCustomRoleId",
        to = "super::roles::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Roles,
    #[sea_orm(has_many = "super::saml_auth_states::Entity")]
    SamlAuthStates,
    #[sea_orm(has_many = "super::saml_consumed_assertions::Entity")]
    SamlConsumedAssertions,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tenants,
    #[sea_orm(has_many = "super::user_saml_identities::Entity")]
    UserSamlIdentities,
}

impl Related<super::departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Departments.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::saml_auth_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlAuthStates.def()
    }
}

impl Related<super::saml_consumed_assertions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlConsumedAssertions.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl Related<super::user_saml_identities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSamlIdentities.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
