//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tenants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(unique)]
    pub domain: String,
    pub plan: String,
    pub status: String,
    pub compliance_mode: String,
    pub encryption_standard: String,
    pub storage_quota_bytes: Option<i64>,
    pub storage_used_bytes: Option<i64>,
    pub retention_policy_days: i32,
    pub max_upload_size_bytes: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub smtp_host: Option<String>,
    pub smtp_port: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub smtp_username: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub smtp_password: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub smtp_from: Option<String>,
    pub smtp_secure: Option<bool>,
    pub enable_totp: Option<bool>,
    pub enable_passkeys: Option<bool>,
    pub mfa_required: Option<bool>,
    pub session_timeout_minutes: Option<i32>,
    pub public_sharing_enabled: Option<bool>,
    pub data_export_enabled: Option<bool>,
    pub blocked_extensions: Option<Vec<String>>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub password_policy: Option<Json>,
    pub ip_allowlist: Option<Vec<String>>,
    pub ip_blocklist: Option<Vec<String>>,
    pub ip_restriction_mode: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub auth_methods: Vec<String>,
    pub approval_workflow_enabled: Option<bool>,
    pub backup_enabled: Option<bool>,
    pub auto_backup_enabled: Option<bool>,
    pub auto_backup_cron: Option<String>,
    pub auto_backup_retention_count: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ai_usage_logs::Entity")]
    AiUsageLogs,
    #[sea_orm(has_many = "super::api_usage::Entity")]
    ApiUsage,
    #[sea_orm(has_many = "super::api_usage_hourly::Entity")]
    ApiUsageHourly,
    #[sea_orm(has_many = "super::approval_policies::Entity")]
    ApprovalPolicies,
    #[sea_orm(has_many = "super::approval_requests::Entity")]
    ApprovalRequests,
    #[sea_orm(has_many = "super::audit_logs::Entity")]
    AuditLogs,
    #[sea_orm(has_one = "super::audit_settings::Entity")]
    AuditSettings,
    #[sea_orm(has_many = "super::automation_jobs::Entity")]
    AutomationJobs,
    #[sea_orm(has_many = "super::backup_history::Entity")]
    BackupHistory,
    #[sea_orm(has_many = "super::deletion_requests::Entity")]
    DeletionRequests,
    #[sea_orm(has_many = "super::departments::Entity")]
    Departments,
    #[sea_orm(has_many = "super::discord_notification_logs::Entity")]
    DiscordNotificationLogs,
    #[sea_orm(has_many = "super::discord_oauth_states::Entity")]
    DiscordOauthStates,
    #[sea_orm(has_many = "super::extension_installations::Entity")]
    ExtensionInstallations,
    #[sea_orm(has_many = "super::extension_webhook_logs::Entity")]
    ExtensionWebhookLogs,
    #[sea_orm(has_many = "super::extensions::Entity")]
    Extensions,
    #[sea_orm(has_many = "super::file_comments::Entity")]
    FileComments,
    #[sea_orm(has_many = "super::file_embeddings::Entity")]
    FileEmbeddings,
    #[sea_orm(has_many = "super::file_exports::Entity")]
    FileExports,
    #[sea_orm(has_many = "super::file_groups::Entity")]
    FileGroups,
    #[sea_orm(has_many = "super::file_requests::Entity")]
    FileRequests,
    #[sea_orm(has_many = "super::file_shares::Entity")]
    FileShares,
    #[sea_orm(has_many = "super::file_summaries::Entity")]
    FileSummaries,
    #[sea_orm(has_many = "super::files_metadata::Entity")]
    FilesMetadata,
    #[sea_orm(has_many = "super::notifications::Entity")]
    Notifications,
    #[sea_orm(has_many = "super::oidc_oauth_states::Entity")]
    OidcOauthStates,
    #[sea_orm(has_many = "super::quarantined_files::Entity")]
    QuarantinedFiles,
    #[sea_orm(has_many = "super::replication_jobs::Entity")]
    ReplicationJobs,
    #[sea_orm(has_many = "super::roles::Entity")]
    Roles,
    #[sea_orm(has_many = "super::saml_auth_states::Entity")]
    SamlAuthStates,
    #[sea_orm(has_many = "super::security_alerts::Entity")]
    SecurityAlerts,
    #[sea_orm(has_many = "super::sso_attribute_mappings::Entity")]
    SsoAttributeMappings,
    #[sea_orm(has_one = "super::tenant_ai_settings::Entity")]
    TenantAiSettings,
    #[sea_orm(has_one = "super::tenant_discord_settings::Entity")]
    TenantDiscordSettings,
    #[sea_orm(has_many = "super::tenant_email_templates::Entity")]
    TenantEmailTemplates,
    #[sea_orm(has_many = "super::tenant_notification_settings::Entity")]
    TenantNotificationSettings,
    #[sea_orm(has_many = "super::tenant_oidc_providers::Entity")]
    TenantOidcProviders,
    #[sea_orm(has_many = "super::tenant_saml_providers::Entity")]
    TenantSamlProviders,
    #[sea_orm(has_many = "super::user_consent::Entity")]
    UserConsent,
    #[sea_orm(has_many = "super::user_discord_connections::Entity")]
    UserDiscordConnections,
    #[sea_orm(has_many = "super::user_malware_counts::Entity")]
    UserMalwareCounts,
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
    #[sea_orm(has_many = "super::virus_scan_jobs::Entity")]
    VirusScanJobs,
    #[sea_orm(has_many = "super::virus_scan_results::Entity")]
    VirusScanResults,
    #[sea_orm(has_one = "super::virus_scan_settings::Entity")]
    VirusScanSettings,
}

impl Related<super::ai_usage_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiUsageLogs.def()
    }
}

impl Related<super::api_usage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiUsage.def()
    }
}

impl Related<super::api_usage_hourly::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiUsageHourly.def()
    }
}

impl Related<super::approval_policies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApprovalPolicies.def()
    }
}

impl Related<super::approval_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApprovalRequests.def()
    }
}

impl Related<super::audit_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditLogs.def()
    }
}

impl Related<super::audit_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditSettings.def()
    }
}

impl Related<super::automation_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AutomationJobs.def()
    }
}

impl Related<super::backup_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BackupHistory.def()
    }
}

impl Related<super::deletion_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeletionRequests.def()
    }
}

impl Related<super::departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Departments.def()
    }
}

impl Related<super::discord_notification_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordNotificationLogs.def()
    }
}

impl Related<super::discord_oauth_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordOauthStates.def()
    }
}

impl Related<super::extension_installations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtensionInstallations.def()
    }
}

impl Related<super::extension_webhook_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtensionWebhookLogs.def()
    }
}

impl Related<super::extensions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Extensions.def()
    }
}

impl Related<super::file_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileComments.def()
    }
}

impl Related<super::file_embeddings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileEmbeddings.def()
    }
}

impl Related<super::file_exports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileExports.def()
    }
}

impl Related<super::file_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileGroups.def()
    }
}

impl Related<super::file_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileRequests.def()
    }
}

impl Related<super::file_shares::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileShares.def()
    }
}

impl Related<super::file_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileSummaries.def()
    }
}

impl Related<super::files_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FilesMetadata.def()
    }
}

impl Related<super::notifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notifications.def()
    }
}

impl Related<super::oidc_oauth_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OidcOauthStates.def()
    }
}

impl Related<super::quarantined_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuarantinedFiles.def()
    }
}

impl Related<super::replication_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReplicationJobs.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::saml_auth_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlAuthStates.def()
    }
}

impl Related<super::security_alerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SecurityAlerts.def()
    }
}

impl Related<super::sso_attribute_mappings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SsoAttributeMappings.def()
    }
}

impl Related<super::tenant_ai_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantAiSettings.def()
    }
}

impl Related<super::tenant_discord_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantDiscordSettings.def()
    }
}

impl Related<super::tenant_email_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantEmailTemplates.def()
    }
}

impl Related<super::tenant_notification_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantNotificationSettings.def()
    }
}

impl Related<super::tenant_oidc_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantOidcProviders.def()
    }
}

impl Related<super::tenant_saml_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantSamlProviders.def()
    }
}

impl Related<super::user_consent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserConsent.def()
    }
}

impl Related<super::user_discord_connections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDiscordConnections.def()
    }
}

impl Related<super::user_malware_counts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMalwareCounts.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::virus_scan_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VirusScanJobs.def()
    }
}

impl Related<super::virus_scan_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VirusScanResults.def()
    }
}

impl Related<super::virus_scan_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VirusScanSettings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
