//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tenant_ai_settings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tenant_id: Uuid,
    pub enabled: bool,
    pub provider: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub api_key_encrypted: Option<String>,
    pub allowed_roles: Vec<String>,
    pub hipaa_approved_only: bool,
    pub sox_read_only: bool,
    pub monthly_token_limit: i32,
    pub daily_request_limit: i32,
    pub tokens_used_this_month: i32,
    pub requests_today: i32,
    pub last_usage_reset: Option<Date>,
    pub maintenance_mode: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub maintenance_message: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub custom_endpoint: Option<String>,
    pub custom_model: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tenants,
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
