//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tenant_oidc_providers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub name: String,
    pub slug: String,
    pub provider_type: String,
    #[sea_orm(column_type = "Text")]
    pub issuer_url: String,
    #[sea_orm(column_type = "Text")]
    pub client_id: String,
    #[sea_orm(column_type = "Text")]
    pub client_secret_encrypted: String,
    #[sea_orm(column_type = "Text")]
    pub scopes: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub authorization_endpoint: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub token_endpoint: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub userinfo_endpoint: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub jwks_uri: Option<String>,
    pub auto_provision: bool,
    pub default_role: String,
    pub default_department_id: Option<Uuid>,
    pub email_domains: Vec<String>,
    pub trust_idp_mfa: bool,
    pub enabled: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::departments::Entity",
        from = "Column::DefaultDepartmentId",
        to = "super::departments::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Departments,
    #[sea_orm(has_many = "super::oidc_oauth_states::Entity")]
    OidcOauthStates,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tenants,
    #[sea_orm(has_many = "super::user_oidc_identities::Entity")]
    UserOidcIdentities,
}

impl Related<super::departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Departments.def()
    }
}

impl Related<super::oidc_oauth_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OidcOauthStates.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl Related<super::user_oidc_identities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserOidcIdentities.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
