//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub department_id: Option<Uuid>,
    pub custom_role_id: Option<Uuid>,
    pub email: String,
    pub name: String,
    pub password_hash: Option<String>,
    pub role: String,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar_url: Option<String>,
    pub allowed_tenant_ids: Option<Vec<Uuid>>,
    pub allowed_department_ids: Option<Vec<Uuid>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub totp_secret: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub recovery_token: Option<String>,
    pub recovery_token_expires_at: Option<DateTimeWithTimeZone>,
    pub password_changed_at: Option<DateTimeWithTimeZone>,
    pub suspended_at: Option<DateTimeWithTimeZone>,
    pub suspended_until: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub suspension_reason: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub dashboard_layout: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub widget_config: Option<Json>,
    pub last_active_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub identity_provider: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ai_usage_logs::Entity")]
    AiUsageLogs,
    #[sea_orm(has_many = "super::api_usage::Entity")]
    ApiUsage,
    #[sea_orm(has_many = "super::audit_logs::Entity")]
    AuditLogs,
    #[sea_orm(has_many = "super::backup_history::Entity")]
    BackupHistory,
    #[sea_orm(
        belongs_to = "super::departments::Entity",
        from = "Column::DepartmentId",
        to = "super::departments::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Departments,
    #[sea_orm(has_many = "super::discord_notification_logs::Entity")]
    DiscordNotificationLogs,
    #[sea_orm(has_many = "super::discord_oauth_states::Entity")]
    DiscordOauthStates,
    #[sea_orm(has_many = "super::extension_installations::Entity")]
    ExtensionInstallations,
    #[sea_orm(has_many = "super::file_comments::Entity")]
    FileComments,
    #[sea_orm(has_many = "super::file_exports::Entity")]
    FileExports,
    #[sea_orm(has_many = "super::file_requests::Entity")]
    FileRequests,
    #[sea_orm(has_many = "super::global_settings::Entity")]
    GlobalSettings,
    #[sea_orm(has_many = "super::notification_preferences::Entity")]
    NotificationPreferences,
    #[sea_orm(has_many = "super::notifications::Entity")]
    Notifications,
    #[sea_orm(has_many = "super::oidc_oauth_states::Entity")]
    OidcOauthStates,
    #[sea_orm(
        belongs_to = "super::roles::Entity",
        from = "Column::CustomRoleId",
        to = "super::roles::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Roles,
    #[sea_orm(has_many = "super::saml_auth_states::Entity")]
    SamlAuthStates,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tenants,
    #[sea_orm(has_many = "super::user_consent::Entity")]
    UserConsent,
    #[sea_orm(has_one = "super::user_discord_connections::Entity")]
    UserDiscordConnections,
    #[sea_orm(has_many = "super::user_login_history::Entity")]
    UserLoginHistory,
    #[sea_orm(has_many = "super::user_malware_counts::Entity")]
    UserMalwareCounts,
    #[sea_orm(has_many = "super::user_oidc_identities::Entity")]
    UserOidcIdentities,
    #[sea_orm(has_one = "super::user_preferences::Entity")]
    UserPreferences,
    #[sea_orm(has_many = "super::user_saml_identities::Entity")]
    UserSamlIdentities,
    #[sea_orm(has_many = "super::user_sessions::Entity")]
    UserSessions,
}

impl Related<super::ai_usage_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiUsageLogs.def()
    }
}

impl Related<super::api_usage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiUsage.def()
    }
}

impl Related<super::audit_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditLogs.def()
    }
}

impl Related<super::backup_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BackupHistory.def()
    }
}

impl Related<super::departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Departments.def()
    }
}

impl Related<super::discord_notification_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordNotificationLogs.def()
    }
}

impl Related<super::discord_oauth_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordOauthStates.def()
    }
}

impl Related<super::extension_installations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtensionInstallations.def()
    }
}

impl Related<super::file_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileComments.def()
    }
}

impl Related<super::file_exports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileExports.def()
    }
}

impl Related<super::file_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileRequests.def()
    }
}

impl Related<super::global_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlobalSettings.def()
    }
}

impl Related<super::notification_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationPreferences.def()
    }
}

impl Related<super::notifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notifications.def()
    }
}

impl Related<super::oidc_oauth_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OidcOauthStates.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::saml_auth_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlAuthStates.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl Related<super::user_consent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserConsent.def()
    }
}

impl Related<super::user_discord_connections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDiscordConnections.def()
    }
}

impl Related<super::user_login_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserLoginHistory.def()
    }
}

impl Related<super::user_malware_counts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMalwareCounts.def()
    }
}

impl Related<super::user_oidc_identities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserOidcIdentities.def()
    }
}

impl Related<super::user_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPreferences.def()
    }
}

impl Related<super::user_saml_identities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSamlIdentities.def()
    }
}

impl Related<super::user_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
