//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user_oidc_identities")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub provider_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub oidc_subject: String,
    #[sea_orm(column_type = "Text")]
    pub oidc_issuer: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub oidc_email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub oidc_name: Option<String>,
    pub last_login_at: Option<DateTimeWithTimeZone>,
    pub login_count: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tenant_oidc_providers::Entity",
        from = "Column::ProviderId",
        to = "super::tenant_oidc_providers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TenantOidcProviders,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::tenant_oidc_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantOidcProviders.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
