[package]
name = "clovalink_auth"
version = "0.1.6"
edition = "2021"

[dependencies]
axum = { workspace = true }
jsonwebtoken = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
clovalink-entity = { workspace = true }
tracing = { workspace = true }
types = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
