[package]
name = "clovalink_auth"
version = "0.1.6"
edition = "2021"

[dependencies]
axum = { workspace = true }
jsonwebtoken = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
clovalink_core = { workspace = true }
types = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }

